package ulite.hello

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration

class HelloProcessor(environment: SymbolProcessorEnvironment) : SymbolProcessor {
    private val codeGenerator: CodeGenerator = environment.codeGenerator

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val annotated = resolver.getSymbolsWithAnnotation("ulite.hello.Hello")
        val names = annotated.filterIsInstance<KSClassDeclaration>()
            .map { it.simpleName.asString() }
            .toList()
        if (names.isEmpty()) {
            return emptyList()
        }
        val kotlinFile = codeGenerator.createNewFile(
            Dependencies(aggregating = false),
            "ulite.hello.generated",
            "HelloGenerated",
        )
        val kotlinSource = buildString {
            append("// Generated by the ksp-hello fixture processor.\n")
            append("package ulite.hello.generated\n\n")
            append(
                "val greetings: List<String> = listOf(" +
                    names.joinToString(", ") { "\"hello from ksp for $it\"" } +
                    ")\n",
            )
        }
        kotlinFile.write(kotlinSource.toByteArray())
        kotlinFile.close()
        return emptyList()
    }
}

class HelloProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        HelloProcessor(environment)
}
